#!/bin/bash

                  #########################################################################################################
                  #                         dcSAGC - delete/create {SYNC, ALIAS, GITHUB, CONFIG} files                    #
                  #                                                                                                       #
                  #         Author: Arpit Bhardwaj(proffapt)                                                              #
                  #         Twitter: @proffapt                                                                            #
                  #         Github: proffapt                                                                              #
                  #         Gitlab:  proffapt                                                                             #
                  #         Instagram: I Don't Use That Shit                                                              #
                  #         Facebook: I Don't Want My Data To Be Available On DarkWeb lol                                 #
                  #         Email: proffapt@protonmail.com                                                                #
                  #                                                                                                       #
                  #               License: BSD License 2.0                                                                #
                  #               Note: If You Find Any BUGS From dcSAGC, PLEASE REPORT IT TO ME!                         #
                  #               Also Email Me If You Have Any Comments / Criticisms Or Suggestions - Thanks             #
                  #                                                                                                       #
                  ######################################################################################################### 

## Colors :

RED=`tput setaf 1`
GREEN=`tput setaf 2`
YELLOW=`tput setaf 3`
BLUE=`tput setaf 4`
PURPLE=`tput setaf 5`
CYAN=`tput setaf 6`
WHITE=`tput setaf 7`
BLACK=`tput setaf 8`
ORANGE=`tput setaf 9`
RESET=$(tput sgr0)

## Usage and arguments :

USAGE="
                  ##############################################################################################################
                  #                         dcSAGC - delete/create {SYNC, ALIAS, GITHUB, CONFIG} files                         #
                  #  Automate the unique process(by proffapt) of syncing your configuration from your local machine to github. #
                  #                                                                                                            #
                  #         Author: Arpit Bhardwaj(proffapt)                                                                   #
                  #         Twitter: @proffapt                                                                                 #
                  #         Github: proffapt                                                                                   #
                  #         Gitlab: proffapt                                                                                   #
                  #         Instagram: I Don't Use That Shit                                                                   #
                  #         Facebook: I Don't Want My Data To Be Available On DarkWeb lol                                      #
                  #         Email: proffapt@protonmail.com                                                                     #
                  #                                                                                                            #
                  #                  License: BSD License 2.0                                                                  #
                  #                  Note: If You Find Any BUGS From dcSAGC, PLEASE REPORT IT TO ME!                           #
                  #                  Also Email Me If You Have Any Comments / Criticisms Or Suggestions - Thanks               #
                  #                                                                                                            #
                  ############################################################################################################## 

USAGE: $(basename "$0") [-m delete/create] [-s <sync_script_location>] [-a <name_of_alias>] [-g <git_main_folder>] [-c <config_file_location>]

where:
    -m : Specify the mode.. either delete or create.
        create : starts the process of creation
        delete : starts the process of deletion
    -s : Enter full location(with name) of syncing script file
    -a : Enter name for the alias to be used to edit the config file
    -g : Enter full location(with name) of directory to be used as main for syncing
    -c : Enter full location(with name) of configuration file
    -h : Show this help message "

while getopts m:s:a:g:c:h input
do
case "${input}"
in
m) MODE=${OPTARG};;
s) SYNC_SCRIPT_location=${OPTARG};;
a) ALIAS=${OPTARG};;
g) GIT_MAIN_FOLDER_location=${OPTARG};;
c) CONFIG_FILE_location=${OPTARG};;
h) echo "${USAGE}" && exit 0 ;;
*)  echo
	echo "Invalid option: -$input" && exit 0 ;;
esac
done

## Extracting names of files and folders from given location :

SYNC_SCRIPT="${SYNC_SCRIPT_location##*/}"
SYNC_SCRIPT_folder="${SYNC_SCRIPT_location%/*}"
git_SYNC_SCRIPT_folder="$SYNC_SCRIPT_folder/.git" ## We got without a '/'
IGIT_FOLDER="$GIT_MAIN_FOLDER_location.git" ## We got with a '/'
CONFIG_FILE="${CONFIG_FILE_location##*/}"

## Script execution location :

CURRENT_LOCATION=$(pwd)

## Creating the syncing files logic :

if [[ $MODE == create ]]; then

    if [[ ! -f "$CONFIG_FILE_location" ]]; then
        echo -e "${GREEN}[+] ${BLUE}Creating configuration file${WHITE}"
        nvim $CONFIG_FILE_location
    else
        echo -e "${YELLOW}[-] ${BLUE}Configuration file already exists!${WHITE}"
    fi

    if [[ ! -d "$GIT_MAIN_FOLDER_location" ]]; then
        echo -e "${GREEN}[+] ${BLUE}Creating local git folder${WHITE}"
        mkdir $GIT_MAIN_FOLDER_location
    else 
        echo -e "${YELLOW}[-] ${BLUE}Local git folder already exists!${WHITE}"
    fi

    if [[ ! -d "$IGIT_FOLDER" ]]; then

        echo -e "${GREEN}[+] ${BLUE}Initialising git in the GIT folder${WHITE}"
        cd $GIT_MAIN_FOLDER_location
        git init
        read -p "$(echo -e "${GREEN}[*] ${CYAN}Enter the git repository link to be used as origin: ${WHITE}")" ORIGIN
        git remote add origin $ORIGIN

        if [[ ! -f "README.md" ]]; then
            echo -e "${GREEN}[+] ${BLUE}Creating README.md file in the git folder${WHITE}"

            nvim README.md
            git add .
            git commit -m "adding README.md file and config file"
            git push origin main
            cd $CURRENT_LOCATION
        else
            echo -e "${YELLOW}[-] ${BLUE}README.md file already exists in the git folder!${WHITE}"
        fi

        echo -e "${GREEN}[+] ${BLUE}Git successfully initialised in the git folder${WHITE}"
    else
        echo -e "${YELLOW}[-] ${BLUE}Git is already initialised in the git folder!${WHITE}"

        cd $GIT_MAIN_FOLDER_location
        if [[ ! -f "README.md" ]]; then
            echo -e "${GREEN}[+] ${BLUE}Creating README.md file in the git folder${WHITE}"
            
            nvim README.md
            git add .
            git commit -m "adding README.md file and config file"
            git push origin main
            cd $CURRENT_LOCATION
        else
            echo -e "${YELLOW}[-] ${BLUE}README.md file already exists in the git folder!${WHITE}"
        fi

    fi

    if [[ ! -f "$GIT_MAIN_FOLDER_location$CONFIG_FILE" ]]; then
        echo -e "${GREEN}[+] ${BLUE}Moving the config file to git folder${WHITE}"
        mv $CONFIG_FILE_location $GIT_MAIN_FOLDER_location
    else
        echo -e "${YELLOW}[-] ${BLUE}Config already exist in the git folder${WHITE}"
    fi

    if [[ ! -f "$CONFIG_FILE_location" ]]; then
        echo -e "${GREEN}[+] ${BLUE}Creating link at config location from config file in git folder${WHITE}"
        ln -s $GIT_MAIN_FOLDER_location$CONFIG_FILE $CONFIG_FILE_location
    else
        echo -e "${YELLOW}[-] ${BLUE}Link already exist in config location${WHITE}"
    fi

    ## creating syncer script
        
    SHELL_LOCATION=$(echo $SHELL)
    SHELL_TYPE="${SHELL_LOCATION##*/}"
        
    if [[ $SHELL_TYPE == fish ]]; then

        if [[ ! -f "$SYNC_SCRIPT_location" ]]; then

            echo -e "${GREEN}[+] ${BLUE}Creating sync script${WHITE}"

            echo "#!/opt/local/bin/fish

set CURR_LOCATION \$(pwd)

cd $GIT_MAIN_FOLDER_location
git add $CONFIG_FILE

echo (set_color blue) '------------------' (set_color normal)
echo (set_color red) 'COMMITTING UPDATE' (set_color normal)
echo (set_color blue) '------------------' (set_color normal)

git commit -m 'updating $CONFIG_FILE via shell script'

echo (set_color blue) '------------------' (set_color normal)
echo (set_color yellow) '  PUSHING UPDATE' (set_color normal)
echo (set_color blue) '------------------' (set_color normal)

git push -u origin main
cd \$CURR_LOCATION

echo (set_color blue) '------------------' (set_color normal)
echo (set_color green) 'SYNCED WITH GITHUB' (set_color normal)
echo (set_color blue) '------------------' (set_color normal)" > $SYNC_SCRIPT_location

            chmod +x $SYNC_SCRIPT_location

            ## If the sync script's folder is related to some git repo.. then update the remote repo..
            if [[ -d "$git_SYNC_SCRIPT_folder" ]]; then
                echo -e "${GREEN}[+] ${BLUE}Syncing the git folder${WHITE}"

                cd $SYNC_SCRIPT_folder
                git add $SYNC_SCRIPT
                git commit -m "initial commit for $SYNC_SCRIPT"
                git push -u origin main
            else
                echo -e "${RED}[!] ${BLUE}The git folder for sync file isn't initialised${WHITE}"
            fi

            ## Updating the shell config file for the alias to edit(and update simultaneously) this config file
            echo -e "${GREEN}[+] ${BLUE}Adding the alias to shell config file${WHITE}"

            echo "alias $ALIAS='nvim $CONFIG_FILE_location && $SYNC_SCRIPT_location'" >> ~/.config/fish/config.fish

            echo
            echo -e "${CYAN}[^] ${YELLOW}Source the shell config after running the script..${WHITE}"
            echo
            
            ## This is the alias to my fish config syncer.. you might change it or remove it according to your case:
            echo -e "${GREEN}[+] ${BLUE}Syncing the shell config file${WHITE}"
            n-fish-ctgs

            ## Syncing the configuration file added in it's git folder using just created sync scripts..
            echo -e "${GREEN}[+] ${BLUE}Syncing the configuration file to github${WHITE}"
            $SYNC_SCRIPT_location

        else
            echo -e "${YELLOW}[-] ${BLUE}Sync file already exist${WHITE}"
        fi

    elif [[ $SHELL_TYPE == bash ]] || [[ $SHELL_TYPE == zsh ]]; then

        if [[ ! -f "$SYNC_SCRIPT_location" ]]; then

            echo -e "${GREEN}[+] ${BLUE}Creating sync script${WHITE}"

            echo "#!/bin/bash

CURR_LOCATION=\$(pwd)

cd $GIT_MAIN_FOLDER_location 
git add $CONFIG_FILE

echo -e '\e[0;91m------------------\e[0m'
echo -e '\e[0;91mCOMMITTING UPDATE\e[0m'
echo -e '\e[0;94m------------------\e[0m'

git commit -m 'updating $CONFIG_FILE via shell script'

echo -e '\e[0;94m------------------\e[0m'
echo -e '  \e[0;33mPUSHING UPDATE\e[0m'
echo -e '\e[0;94m------------------\e[0m'

git push -u origin main
cd \$CURR_LOCATION

echo -e '\e[0;94m------------------\e[0m'
echo -e '\e[0;92mSYNCED WITH GITHUB\e[0m'
echo -e '\e[0;94m------------------\e[0m' " > $SYNC_SCRIPT_location
            
            chmod +x $SYNC_SCRIPT_location

            ## If the sync script's folder is related to some git repo.. then update the remote repo..
            if [[ -d "$git_SYNC_SCRIPT_folder" ]]; then
                echo -e "${GREEN}[+] ${BLUE}Syncing the git folder${WHITE}"

                cd $SYNC_SCRIPT_folder
                git add $SYNC_SCRIPT 
                git commit -m "initial commit for $SYNC_SCRIPT"
                git push -u origin main
            else
                echo -e "${RED}[!] ${BLUE}The git folder for sync file isn't initialised${WHITE}"
            fi

            echo -e "${GREEN}[+] ${BLUE}Adding the alias to shell config file and sourcing it${WHITE}"
            
            SHELL_file="${SHELL_TYPE}rc"
            echo " " >> ~/.$SHELL_file
            echo "  alias $ALIAS='nvim $CONFIG_FILE_location && $SYNC_SCRIPT_location'" >> ~/.$SHELL_file
            source ~/.$SHELL_file

            ## Syncing the configuration file added in it's git folder using just created sync scripts..
            echo -e "${GREEN}[+] ${BLUE}Syncing the configuration file to github${WHITE}"
            $SYNC_SCRIPT_location

        else
            echo -e "${YELLOW}[-] ${BLUE}Sync file already exist${WHITE}"
        fi

    fi

elif [[ $MODE == delete ]]; then

    if [[ -f "$CONFIG_FILE_location" ]]; then
        echo -e "${GREEN}[+] ${BLUE}Removing link of configuration file${WHITE}"
        rm $CONFIG_FILE_location
    else
        echo -e "${RED}[!] ${BLUE}Configuration link file doesn't exist!${WHITE}"
    fi

    echo -e "${GREEN}[+] ${BLUE}Putting original file back to it's expected location..${WHITE}"
    cp $GIT_MAIN_FOLDER_location$CONFIG_FILE $CONFIG_FILE_location

    if [[ -f "$GIT_MAIN_FOLDER_location$CONFIG_FILE" ]]; then
        rm -rf $GIT_MAIN_FOLDER_location
    else
        echo -e "${RED}[!] ${BLUE}Git folder containing configuration file doesn't exist!${WHITE}"
    fi
    
    if [[ -f "$SYNC_FILE_location" ]]; then
        rm $SYNC_FILE_location
    else
        echo -e "${RED}[!] ${BLUE}Configuration syncer script doesn't exist!${WHITE}"
    fi

else 

    echo -e "${RED}ERROR${WHITE}: Invalid mode selected - '${ORANGE}$1${WHITE}'"
    echo -e "${RED}[!] ${WHITE}Exitting the tool.."

fi