#!/bin/bash

# Functions for delete mode
# <start>
delete_link() {
	if [[ -f "$CONFIG_FILE_location" ]]; then
		if [[ -L "$CONFIG_FILE_location" ]]; then echo -e "${GREEN}[+] ${BLUE}Removing configuration 'link file'${WHITE}"

			rm "$CONFIG_FILE_location"
		else
			echo -e "${YELLOW}[-] ${BLUE}This file at configuration location is not a link!${WHITE}"
		fi
	else
		echo -e "${YELLOW}[-] ${BLUE}Configuration 'link file' doesn't exist!${WHITE}"
	fi
}

put_back_config_file() {
	if [[ -f "$new_CONFIG_FILE_LOCATION" ]]; then
		echo -e "${GREEN}[+] ${BLUE}Putting configuration file back to it's original location from github folder${WHITE}"

		mv "$new_CONFIG_FILE_LOCATION" "$CONFIG_FILE_location"
	else
		echo -e "${YELLOW}[-] ${BLUE}Configuration file doesn't exist in the github folder!${WHITE}"
	fi
}

delete_git_folder_and_repo() {
	if [[ -d "$GIT_MAIN_FOLDER_location" ]]; then
		cd "$GIT_MAIN_FOLDER_location" || exit

		FILE_COUNT=$(find . ! \( -name . -o -name .. -o -name .git -o -name README.md -o -name .gsync_init -o -name .gitignore \) -maxdepth 1 | grep -e "^" -c)

		## updating repo
		echo -e "${GREEN}[+] ${BLUE}Updating the remote repo${WHITE}"
		git add $CONFIG_FILE
		git commit -m "Removing $CONFIG_FILE via gsync by @proffapt"
		git push origin

		## for further detecting the number of branches
		echo -e "${GREEN}[+] ${BLUE}Updating remote branch list${WHITE}"
		git pull origin
		BRANCH_COUNT=$(git branch -r | grep -e "^" -c)

		if [[ $FILE_COUNT == "0" ]] && [[ $BRANCH_COUNT == "1" ]]; then
			echo -e "${GREEN}[+] ${BLUE}Deleting the github repository containing configuration file${WHITE}"
			gh repo delete --confirm

			cd "$CURRENT_LOCATION" || exit

			echo -e "${GREEN}[+] ${BLUE}Deleting the github folder containing configuration file from your local machine${WHITE}"
			rm -rf "$GIT_MAIN_FOLDER_location"
		elif [[ $FILE_COUNT != "0" ]] && [[ $BRANCH_COUNT == "1" ]]; then
			echo -e "${CYAN}[~] ${BLUE}Detected more than one configuration file in the github folder${WHITE}"
			echo -e "${YELLOW}[-] ${BLUE}Skipping deletion of github repo and the folder${WHITE}"

			cd "$CURRENT_LOCATION" || exit
		elif [[ $FILE_COUNT == "0" ]] && [[ $BRANCH_COUNT != "1" ]]; then
			echo -e "${CYAN}[~] ${BLUE}Detected more than one branch in the github repo${WHITE}"
			echo -e "${YELLOW}[-] ${BLUE}Skipping deletion of github repo${WHITE}"

			echo -e "${GREEN}[+] ${BLUE}Deleting the branch containing the config file${WHITE}"
			DEL_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
			git push --delete origin $DEL_BRANCH

			cd "$CURRENT_LOCATION" || exit

			echo -e "${GREEN}[+] ${BLUE}Deleting the github folder containing configuration file from your local machine${WHITE}"
			rm -rf "$GIT_MAIN_FOLDER_location"
		else
			echo -e "${CYAN}[~] ${BLUE}Detected more than one branch github repo${WHITE}"
			echo -e "${CYAN}[~] ${BLUE}Detected more than one configuration file in the github folder${WHITE}"

			cd "$CURRENT_LOCATION" || exit
 		fi
	else
		echo -e "${YELLOW}[-] ${BLUE}Github folder supposed to be containing configuration file doesn't exist!${WHITE}"
	fi
}

deconfigure_syncsript(){
	if [[ $FILE_COUNT == 0 ]]; then ## if there are no other file in the github folder: remove it's entry
		## adding this check just to make the code robust in terms of functioning
		ENTRY_TEST=$(grep "$STARTUP_SCRIPT" -ce "$GIT_MAIN_FOLDER_location")

		if [[ $ENTRY_TEST != 0 ]]; then
			echo -e "${GREEN}[+] ${BLUE}Deleting folder's entry${WHITE}"

			if [[ $KERNEL == "Darwin" ]]; then
				## remove the entry of that github folder from startup.sh
				## command specific to BSD sed
				sed -i '' "\:$GIT_MAIN_FOLDER_location:d" "$STARTUP_SCRIPT"
				## executing the script again after editing it
				"$STARTUP_SCRIPT"
			else
				## remove the entry of that github folder from startup.sh
				## command specific to GNU sed
				sed -i "\:^$GIT_MAIN_FOLDER_location:d" "$STARTUP_SCRIPT"

				## copying the modified file without entry of that github folder
				cp "$STARTUP_SCRIPT" /etc/profile.d/gsync-startup.sh
				## executing the script again after editing it
				/etc/profile.d/gsync-startup.sh
			fi
		else
			echo -e "${YELLOW}[-] ${BLUE}Entry for the specified github folder already doesn't exist${WHITE}"
		fi
	else ## if there are other configuration files then skip the process of deletion of entry
		echo -e "${YELLOW}[-] ${BLUE}Skipping deletion of this folder's entry${WHITE}"
	fi

	ENTRY_COUNT=$(grep "$STARTUP_SCRIPT" -ce "-d")

	if [[ $ENTRY_COUNT == 0 ]]; then ## if it has exactly three lines: that is no entry
		echo -e "${CYAN}[~] ${BLUE}No other entry detected${WHITE}"
		echo -e "${GREEN}[+] ${BLUE}Removing startup script${WHITE}"

		if [[ $KERNEL == "Darwin" ]]; then
			## remove startup.sh and com.gsync-startup.plist
			rm "$STARTUP_SCRIPT"
			rm ~/Library/LaunchAgents/com.gsync-startup.plist
		else
			## remove startup.sh and gsync-startup.sh
			rm "$STARTUP_SCRIPT"
			rm /etc/profile.d/gsync-startup.sh
		fi
	else ## if the startup.sh has more than 3 lines
		echo -e "${CYAN}[~] ${BLUE}Detected other entries${WHITE}"
		echo -e "${YELLOW}[-] ${BLUE}Skipping removal of startup script${WHITE}"
	fi
}
