#!/bin/bash

# handler functions
# <start>

_EXIT_() {
	echo -e "${RED}[!] ${WHITE}Exitting the tool..${WHITE}"
	echo

	exit 0
}

ERROR_invalid_input() {
	echo -e "${RED}ERROR:${BLUE} Invalid choice selected${WHITE}"
	_EXIT_
}
# </start>
