#!/bin/bash

# handler functions
# <start>
MSG_source_shell_config_file() {
	echo -e "${CYAN}[^]${WHITE} ${YELLOW}Source your SHELL config file..${WHITE}"
}

_EXIT_(){
    echo -e "${RED}[!] ${WHITE}Exitting the tool..${WHITE}"
    echo

    exit 0
}

ERROR_invalid_input(){
    echo -e "${RED}ERROR:${BLUE} Invalid choice selected${WHITE}"
    _EXIT_
}
# </start>