#!/bin/bash

# Getting input for the directory to monitor on
while [ $OPTIND -le "$#" ]; do
	if getopts d: input; then
		case "${input}" in

		d) TARGETDIR=${OPTARG} ;;
		*)
			exit 0
			;;
		esac
	else
		script_args+=("${!OPTIND}")
		((OPTIND++))
	fi
done

set -e

stderr() {
	echo "$1" >&2
}

is_command() {
	command -v "$1" &>/dev/null
}

if [ "$(uname)" != "Darwin" ]; then
	# If you don't have default location then update the location for inotifywait binary
	INW="/usr/bin/inotifywait"
	EVENTS="close_write,move,delete,create"
	INCOMMAND="\"$INW\" -qr -e \"$EVENTS\" --exclude \"\.git\" \"$TARGETDIR\""

	# Storing full path to other binaries being used
	TO="/usr/bin/timeout"
	GIT="/usr/bin/git"
else
	# If not installed using brew change the location for fswatch binary
	INW="/opt/homebrew/bin/fswatch"
	# 414 = MovedTo + MovedFrom + Renamed + Removed + Updated + Created
	#                = 256 + 128+ 16 + 8 + 4 + 2
	EVENTS="--event=414"
	INCOMMAND="\"$INW\" --recursive \"$EVENTS\" --exclude \"\.git\" --one-event \"$TARGETDIR\""

	# Storing full path to other binaries being used
	TO="/opt/homebrew/bin/timeout"
	GIT="/opt/homebrew/bin/git"
fi

for cmd in "$GIT" "$INW" "$TO"; do
	# in OSX: `timeout` => brew install coreutils
	# in OSX: `fswatch` => brew install fswatch
	is_command "$cmd" || {
		stderr "Error: Required command '$cmd' not found"
		exit 1
	}
done

cd "$TARGETDIR"
echo "$INCOMMAND"

while true; do
	# time used is in seconds
	eval "$TO 60 $INCOMMAND" || true
	STATUS=$(git status -s)
	if [ -n "$STATUS" ]; then
		$GIT add .
		$GIT commit -m "updating via gsync-syncscript by @proffapt"
		$GIT push origin
	fi
done
